# componentDidCatch

componentDidCatch 라는 생명주기 메서드를 이용하여 리액트 애플리케이션에서 발생하는 에러를 처리할 수 있다.

## 리액트 앱에서 에러가 발생하는 상황

```
function User({ user }) {
  if (!user) {
    return null;
  }

  return (
    <div>
      <div>
        <b>ID</b>: {user.id}
      </div>
      <div>
        <b>Username:</b> {user.username}
      </div>
    </div>
  );
}

export default User;
```

이렇게 코드를 작성하면 user 값이 존재하지 않을 때 에러를 표시하는 것이 아니라 null 을 렌더링하여 아무것도 나타나지 않게 되고, 이를 null checking 이라고 한다.

데이터를 네트워크 요청을 통하여 나중에 데이터를 받아오게 되는 상황에 데이터가 없으면 null 을 보여주거나 로딩중 과 같은 결과물을 렌더링하는데 사용된다.

```
function Users({ users, onToggle }) {
  if (!users) return null;

  return (
    <ul>
      {users.map(user => (
        <li key={user.id} onClick={() => onToggle(user.id)}>
          {user.username}
        </li>
      ))}
    </ul>
  );
}

Users.defaultProps = {
  onToggle: () => {
    console.warn('onToggle is missing!');
  }
};
```

위의 코드에서 onToggle 이라는 함수를 props 로 받지 못한다면 에러가 발생하게 되지만, defaultProps 를 설정함으로써 확인해줄 수 있다.

## componentDidCatch 로 에러 잡아내기

componentDidCatch 생명주기 메서드를 사용하면 사전에 예외처리하지 않는 에러가 발생했을 때 사용자에게 에러가 발생했다고 알려주는 화면을 보여줄 수 있다.

```
import React, { Component } from 'react';

class ErrorBoundary extends Component {
  state = {
    error: false
  };

  componentDidCatch(error, info) {
    console.log('에러가 발생했습니다.');
    console.log({
      error,
      info
    });
    this.setState({
      error: true
    });
  }

  render() {
    if (this.state.error) {
      return <h1>에러 발생!</h1>;
    }
    return this.props.children;
  }
}

export default ErrorBoundary;
```

componentDidCatch 메서드에서 첫번째 파라미터는 에러의 내용, 두번째 파라미터는 에러의 위치를 알려준다.

위의 컴포넌트로 에러를 체크하고 싶은 컴포넌트를 감싸주면 에러 체크를 할 수 있다.

```
import React from 'react';
import User from './User';
import ErrorBoundary from './ErrorBoundary';

function App() {
  const user = {
    id: 1,
    username: 'velopert'
  };
  return (
    <ErrorBoundary>
      <User />
    </ErrorBoundary>
  );
}

export default App;
```

## Sentry 연동

componentDidCatch 를 사용해서 앱에서 에러가 발생했을 때 사용자에게 에러가 발생했음을 인지시켜줄 수는 있지만, componentDidCatch 가 실제로 호출되는 일은 없어야 한다. 만약 놓친 에러가 있다면 알아내어 예외처리를 해주어야 한다.

개발자가 놓치고 사용자가 찾게되는 에러가 있다면 componentDidCatch 에서 error 와 Info 값을 네트워크를 통하여 전달해주면 좋다.

이를 위해서 따로 서버를 만드는 것은 번거롭기에, Sentry 라는 사용서비스에서 이러한 작업을 해주게 된다.
